# Generated by Django 4.1.1 on 2022-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('UserAddress', models.CharField(max_length=200)),
                ('UserAge', models.IntegerField(max_length=100)),
                ('UserProfession', models.CharField(max_length=200)),
                ('UserSportInterestRate', models.IntegerField(max_length=100)),
            ],
        ),
    ]
